version: "3.8"

services:
  spring:
    image: "spring-ias-prod-container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - IAS

networks:
  IAS:
    driver: bridge
