name: SpringBoot CI with Gradle

on:
  push:
    branches:
      - CICD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: create properties for CI Test
        run: |
          cd src/main/resources
          echo "${{ secrets.OAUTH_PROPERTIES }}" > oauth.properties
          echo "${{ secrets.SECURITY_PROPERTIES }}" > security.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: |
          ./gradlew --info test

