name: SpringBoot CI with Gradle

on:
  push:
    branches:
      - CICD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: create properties for CI Test
        run: |
          cd src/main/resources
          echo "${{ secrets.OAUTH_PROPERTIES }}" > oauth.properties
          echo "${{ secrets.SECURITY_PROPERTIES }}" > security.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: |
          ./gradlew --info test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: check
        run: |
          cd ..
          ls -al
          pwd
      - name: SCP Action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_4800H }}
          username: ${{ secrets.USERNAME_4800H }}
          key: ${{ secrets.PRIVATE_KEY_4800H }}
          source: "build/libs/*.jar, Dockerfile, docker-compose-spring.yml"
          target: "~/prod/ias"

      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_4800H }}
          username: ${{ secrets.USERNAME_4800H }}
          key: ${{ secrets.PRIVATE_KEY_4800H }}
          script: |
            cd ~/prod/ias
            docker-compose -f docker-compose-spring.yml up -d


